routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes([
    'register'  => false,
    'reset'     => false,
    'verify'    => false,
]);


/** Website Routes */
Route::get('/', function () {
    return view('website.index');
})->name('home');

Route::get('/blog', [\App\Http\Controllers\Website\BlogController::class, 'index']);
Route::get('/blog/{blog:slug}', [\App\Http\Controllers\Website\BlogController::class, 'show']);
Route::get('/what-our-customers-say-about-us', [\App\Http\Controllers\Website\TestimonialController::class, 'index']);


/** Admin Routes */
Route::group([
    'as'         => 'admin.',
    'middleware' => 'auth',
    'prefix'     => 'admin',
], function () {
    Route::get('/', [App\Http\Controllers\Admin\AdminController::class, 'index'])->name('index');
    Route::resource('blog', \App\Http\Controllers\Admin\BlogController::class)->only([
        'create',
        'edit',
        'index',
        'update',
        'store'
    ]);
    Route::get('/testimonial', [App\Http\Controllers\Admin\TestimonialController::class, 'index'])->name('index');
    Route::resource('testimonial', \App\Http\Controllers\Admin\TestimonialController::class)->only([
        'create',
        'edit',
        'index',
        'update',
        'store'
    ]);
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'image_url',
        'is_live',
        'main_content',
        'published_at',
        'additional_details',
        'slug',
        'title',
        'expired_at'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'featured_at'   => 'datetime',
        'expired_at'    => 'datetime',
        'is_live'       => 'boolean',
        'published_at'  => 'datetime',
    ];
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Blog\BlogStoreRequest;
use App\Http\Requests\Admin\Blog\BlogUpdateRequest;
use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    public function create(Blog $blog)
    {
        return view('admin.blog.create');
    }

    public function edit(Blog $blog)
    {
        return view('admin.blog.edit')->with([
            'blog' =>  $blog
        ]);
    }

    public function index(Request $request)
    {
        $blogs = Blog::query();

        if ($request->get('search')) {
            $blogs->where('title', 'like', '%' . $request->get('search') . '%');
        }

        $blogs = $blogs
            ->orderBy('title', 'asc')
            ->paginate();

        return view('admin.blog.index')->with([
            'blogs' => $blogs
        ]);
    }

    public function store(BlogStoreRequest $request)
    {
        $blog = Blog::create($request->validated());

        return redirect(route('admin.blog.store', $blog))->with([
            'success' => 'Successfully Created a new Blog Post.'
        ]);
    }

    public function update(BlogUpdateRequest $request, Blog $blog)
    {
        $blog->update($request->validated());
        $blog->refresh();

        return redirect(route('admin.blog.edit', $blog))->with([
            'success' => 'Successfully Edited the Blog Post.'
        ]);
    }
}

app/Http/Controllers/Api/BlogController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Blog;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    public function featured(Request $request) : JsonResponse
    {
        $now = Carbon::now();
        $blogs = Blog::whereNotNull('featured_at')
            ->where('featured_at', '<=', $now)
            ->where('published_at', '<=', $now)
            ->where(function ($subquery) use ($now) {
                return $subquery->where('expired_at', '>', $now)->orWhereNull('expired_at');
            })
            ->limit($request->get('limit', 3))
            ->latest('featured_at')
            ->get();

        return response()->json($blogs);
    }

    public function latest(Request $request) : JsonResponse
    {
        $now = Carbon::now();
        $blogs = Blog::whereNotNull('published_at')
            ->where('published_at', '<=', $now)
            ->where(function ($subquery) use ($now) {
                return $subquery->where('expired_at', '>', $now)->orWhereNull('expired_at');
            })
            ->limit($request->get('limit', 9))
            ->latest('published_at')
            ->get();

        return response()->json($blogs);
    }

}

app/Http/Controllers/Website/BlogController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\Blog;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    public function index()
    {
        $now = Carbon::now();
        $blogs = Blog::query()->where('published_at', '<=', $now)
            ->latest('published_at')
            ->paginate(12);

        return view('website.blog.index')->with([
            'blogs' => $blogs
        ]);
    }

    public function show($slug)
    {
        $blog = Blog::query()
            ->where('slug', $slug)
            ->first();
        return view('website.blog.show')->with([
            'blog' => $blog
        ]);
    }

}

resources/views/admin/blog/create.blade.php
@extends('layouts.admin')

@section('content')
    <?php $now = Carbon\Carbon::now() ?>

    <div class="panel">
        <div class="header bg-primary pb-6 pt-5 pt-md-6">
            <div class="container-fluid">
                <div class="header-body">
                    <div class="row align-items-center py-4">
                        <div class="col-lg-6 col-7">
                            <h6 class="h2 text-white d-inline-block mb-0">Blog Posts</h6>
                            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.index') }}"><i class="fas fa-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{{ route('admin.blog.index') }}">Blog Posts</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">New</li>
                                </ol>
                            </nav>
                        </div>
                        <div class="col-lg-6 col-5 text-right">
                            <a href="{{ route('admin.blog.index') }}" class="btn btn-sm btn-neutral">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Page content -->
        <div class="container-fluid mt--6">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <form action="{{ route('admin.blog.store') }}" method="POST">
                            {{ csrf_field() }}
                            <!-- Card header -->
                            <div class="card-header">
                                <h3 class="mb-3">New Blog Post</h3>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">

                                @if(count($errors))
                                    <div class="alert alert-danger">
                                        <ul class="mb-0">
                                            @foreach($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                <div class="form-group">
                                    <label
                                        for="title"
                                        class="form-control-label"
                                    >
                                        Title
                                    </label>
                                    <input
                                        id="title"
                                        class="form-control"
                                        name="title"
                                        placeholder="Blog Title"
                                        required
                                        type="text"
                                        value="{{ old('title') }}"
                                    />
                                </div>

                                <div class="form-group">
                                    <label
                                        for="slug"
                                        class="form-control-label"
                                    >
                                        Slug
                                    </label>
                                    <input
                                        id="slug"
                                        class="form-control"
                                        name="slug"
                                        placeholder="Blog Slug"
                                        required
                                        type="text"
                                        value="{{ old('slug') }}"
                                    />
                                </div>

                                <div class="form-group">
                                    <label
                                        for="image_url"
                                        class="form-control-label"
                                    >
                                        Image Url
                                    </label>
                                    <input
                                        id="image_url"
                                        class="form-control"
                                        name="image_url"
                                        placeholder="Blog Image URL"
                                        required
                                        type="text"
                                        value="{{ old('image_url') }}"
                                    />
                                </div>

                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="published_at"
                                                class="form-control-label"
                                            >
                                                Publish Date
                                            </label>
                                            <input
                                                id="published_at"
                                                class="form-control"
                                                name="published_at"
                                                type="datetime-local"
                                                value="{{ old('published_at') }}"
                                            />
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="featured_at"
                                                class="form-control-label"
                                            >
                                                Featured Date
                                            </label>
                                            <input
                                                id="featured_at"
                                                class="form-control"
                                                name="featured_at"
                                                type="datetime-local"
                                                value="{{ old('featured_at') }}"
                                            />
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="expiry_date"
                                                class="form-control-label"
                                            >
                                                Expiry Date
                                            </label>
                                            <input
                                                id="expired_at"
                                                class="form-control"
                                                name="expired_at"
                                                type="datetime-local"
                                                value="{{ old('expired_at') }}"
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label
                                        for="main_content"
                                        class="form-control-label"
                                    >
                                        Main Content
                                    </label>
                                    <textarea
                                        id="main_content"
                                        class="form-control"
                                        name="main_content"
                                        required
                                        rows="5"
                                        type="text"
                                    >{{ old('main_content') }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label
                                        for="image_url"
                                        class="form-control-label"
                                    >
                                        Additional details
                                    </label>
                                    <input
                                        id="additional_details"
                                        class="form-control"
                                        name="additional_details"
                                        placeholder="Additional details"
                                        required
                                        type="text"
                                        value="{{ old('additional_details') }}"
                                    />
                                </div>
                            </div>
                            <!-- Card footer -->
                            <div class="card-footer py-4 text-right">
                                <button
                                    class="btn btn-primary"
                                    type="submit"
                                >
                                    Create
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
@endpush

resources/views/admin/blog/edit.blade.php
@extends('layouts.admin')

@section('content')
    <?php $now = Carbon\Carbon::now() ?>

    <div class="panel">
        <div class="header bg-primary pb-6 pt-5 pt-md-6">
            <div class="container-fluid">
                <div class="header-body">
                    <div class="row align-items-center py-4">
                        <div class="col-lg-6 col-7">
                            <h6 class="h2 text-white d-inline-block mb-0">Blog Posts</h6>
                            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.index') }}"><i class="fas fa-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="{{ route('admin.blog.index') }}">Blog Posts</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                                </ol>
                            </nav>
                        </div>
                        <div class="col-lg-6 col-5 text-right">
                            <a href="{{ route('admin.blog.index') }}" class="btn btn-sm btn-neutral">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Page content -->
        <div class="container-fluid mt--6">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <form action="{{ route('admin.blog.update', $blog) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <!-- Card header -->
                            <div class="card-header">
                                <h3 class="mb-3">Edit Blog Post</h3>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">

                                @if(count($errors))
                                    <div class="alert alert-danger">
                                        <ul class="mb-0">
                                            @foreach($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                @if(session('success'))
                                    <div class="alert alert-success">
                                        <p class="mb-0">{{ session('success') }}</p>
                                    </div>
                                @endif

                                <div class="form-group">
                                    <label
                                        for="title"
                                        class="form-control-label"
                                    >
                                        Title
                                    </label>
                                    <input
                                        id="title"
                                        class="form-control"
                                        name="title"
                                        placeholder="Blog Title"
                                        required
                                        type="text"
                                        value="{{ old('title') ?? ($blog->title ?? '') }}"
                                    />
                                </div>

                                <div class="form-group">
                                    <label
                                        for="slug"
                                        class="form-control-label"
                                    >
                                        Slug
                                    </label>
                                    <input
                                        id="slug"
                                        class="form-control"
                                        name="slug"
                                        placeholder="Blog Slug"
                                        required
                                        type="text"
                                        value="{{ old('slug') ?? ($blog->slug ?? '') }}"
                                    />
                                </div>

                                <div class="form-group">
                                    <label
                                        for="image_url"
                                        class="form-control-label"
                                    >
                                        Image Url
                                    </label>
                                    <input
                                        id="image_url"
                                        class="form-control"
                                        name="image_url"
                                        placeholder="Blog Image URL"
                                        required
                                        type="text"
                                        value="{{ old('image_url') ?? ($blog->image_url ?? '') }}"
                                    />
                                </div>

                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="published_at"
                                                class="form-control-label"
                                            >
                                                Publish Date
                                            </label>
                                            <input
                                                id="published_at"
                                                class="form-control"
                                                name="published_at"
                                                type="datetime-local"
                                                value="{{ old('published_at') ?? ($blog->published_at ? $blog->published_at->toDateTimeLocalString() : '') }}"
                                            />
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="featured_at"
                                                class="form-control-label"
                                            >
                                                Featured Date
                                            </label>
                                            <input
                                                id="featured_at"
                                                class="form-control"
                                                name="featured_at"
                                                type="datetime-local"
                                                value="{{ old('featured_at') ?? ($blog->featured_at ? $blog->featured_at->toDateTimeLocalString() : '') }}"
                                            />
                                        </div>
                                    </div>

                                    <div class="col-4">
                                        <div class="form-group">
                                            <label
                                                for="expired_at"
                                                class="form-control-label"
                                            >
                                                Expiry Date
                                            </label>
                                            <input
                                                id="expired_at"
                                                class="form-control"
                                                name="expired_at"
                                                type="datetime-local"
                                                value="{{ old('expired_at') ?? ($blog->expired_at ? $blog->expired_at->toDateTimeLocalString() : '') }}"
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label
                                        for="main_content"
                                        class="form-control-label"
                                    >
                                        Main Content
                                    </label>
                                    <textarea
                                        id="main_content"
                                        class="form-control"
                                        name="main_content"
                                        required
                                        rows="5"
                                        type="text"
                                    >{{ old('main_content') ?? ($blog->main_content ?? '') }}</textarea>
                                </div>
                            </div>
                            <!-- Card footer -->
                            <div class="card-footer py-4 text-right">
                                <button
                                    class="btn btn-primary"
                                    type="submit"
                                >
                                    Save
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
@endpush